version: '3.1'

services:
  db:
    image: mysql
    container_name: mysqlDB
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./init-database.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
  client:
    container_name: React-App
    build: ./405-react-project/
    ports:
     - 3000:3000
    stdin_open: true
    tty: true
  server:
    container_name: PHP-API
    build: ./php_server/
    ports:
     - 9090:80
volumes:
  db_data: